# Generated by Django 2.2.7 on 2019-11-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='duration',
            field=models.IntegerField(blank=True),
        ),
    ]
