# Generated by Django 2.2.7 on 2019-11-17 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20191117_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videomodel',
            name='duration',
            field=models.FloatField(blank=True),
        ),
    ]
